// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANwAnmeIRFWNHAokXtagvtnOKg2IrE6BU',
    appId: '1:367717799867:web:e28c8f9e7fe83cc72b969e',
    messagingSenderId: '367717799867',
    projectId: 'aper-club',
    authDomain: 'aper-club.firebaseapp.com',
    storageBucket: 'aper-club.appspot.com',
    measurementId: 'G-DG4FDHMCGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIrvxZXbn_c5EFYNTYGeXECoVlcGE5_k',
    appId: '1:367717799867:android:bc01b35871089dcf2b969e',
    messagingSenderId: '367717799867',
    projectId: 'aper-club',
    storageBucket: 'aper-club.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMdBDAJm5baNkovdB9HCDXtgXukaYCBAI',
    appId: '1:367717799867:ios:635886d7b6e581962b969e',
    messagingSenderId: '367717799867',
    projectId: 'aper-club',
    storageBucket: 'aper-club.appspot.com',
    iosBundleId: 'com.aper.app',
  );
}
